### ISSUE TITLE
from cyvcf2 import VCF error

### ISSUE THREAD

**Issue by fjptwenger** [brentp/cyvcf2#104]
```
Python 3.6.6 (default, Nov  6 2018, 12:51:36) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cyvcf2 import VCF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
ImportError: /usr/local/lib/python3.6/site-packages/cyvcf2/cyvcf2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: EVP_sha1

```

 how can I solve this error?

**Comment by brentp** [comment]
you'll have to install libcrypto on your system. or you can clone cyvcf2 from git, build htslib without crypto and then re-install, there's an example of this process in the readme.
the install is currently not ideal, but I haven't had time to resolve all these problems.

**Comment by fjptwenger** [comment]
thanks, it can solved by `apt-get install libcurl4-openssl-dev`

**Comment by raqueldias** [comment]
I still have the same problem even after installing libcurl4-openssl-dev.
`raqueld@cudalord:~/MV/MV_positions_Doug_method/chr22$ sudo apt-get install libcurl4-openssl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libcurl4-openssl-dev is already the newest version (7.58.0-2ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.
raqueld@cudalord:~/MV/MV_positions_Doug_method/chr22$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cyvcf2 import VCF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
ImportError: /usr/local/lib/python3.6/dist-packages/cyvcf2/cyvcf2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: EVP_sha1
>>>
`

**Comment by brentp** [comment]
hi, you'll need to have libcrypto on your system.
