### ISSUE TITLE
installation using pip fails

### ISSUE THREAD

**Issue by BenjaminPeter** [brentp/cyvcf2#28]
When trying to install cyvcf2 using pip:
`sudo pip3 install cyvcf2`
the installation works, but unfortunately importing fails with the following error message:

```
In [2]: from cyvcf2 import VCF                                                                 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-b1d6330f36e2> in <module>()
----> 1 from cyvcf2 import VCF

home/bpeter/.local/lib/python3.4/site-packages/cyvcf2/__init__.py in <module>()
----> 1 from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
      2                      par_het)
      3 Reader = VCFReader = VCF
      4 
      5 __version__ = "0.6.4"

ImportError: No module named 'cyvcf2.cyvcf2'
```

installing directly from github worked fine, however.

**Comment by brentp** [comment]
@juliangehring any ideas? Install works for me on python2.

**Comment by juliangehring** [comment]
I also see that with python3, installing 0.6.4 from pip works, but any imports fail. Older versions from pip import without problems. Installing from source as well as build the wheel and installing with pip works fine for all versions. 

I'm not sure what is causing this. I would think that the changes between 0.6.4 and 0.6.5 should not play a role here, and the issue may be specific for the builds from pypi. @brentp Is it possible to trigger "rebuilding" the 0.6.5 wheel on pypi?

**Comment by juliangehring** [comment]
Just for the record, building from pypi with `pip install --no-binary cyvcf2 --no-cache-dir cyvcf2` also works fine.

**Comment by brentp** [comment]
I just pushed 0.6.5 to pypi and run "pip3.5 install -U cyvcf2" and I'm able to import without problems. Can you verify?

**Comment by BenjaminPeter** [comment]
yes, I can confirm that installation works on my systems. Thanks for the quick fix!

**Comment by dnil** [comment]
Sorry, still having the same issue with the current pip Wheel as above (```ImportError: No module named 'cyvcf2.cyvcf2'```) when installing 0.6.5 via a requirements.txt with pip 9.0.1 in a fresh conda python=3.5 environment. 

The above suggestion from @juliangehring with ```pip install --no-binary cyvcf2 --no-cache-dir cyvcf2``` works like a charm. Can one make that work in a requirements.txt?

**Comment by brentp** [comment]
@dnil can you try removing ~/.cache/pip if you're on linux or ~/Library/Caches/pip
 on OSX and try again?

**Comment by dnil** [comment]
Interesting! Yep, appeared to work on OSX now, but failed on linux for some arcane reason. I'll try to isolate it..

**Comment by brentp** [comment]
it may still be something related to cyvcf2, so feel free to post the new traceback.

**Comment by dnil** [comment]
Ok, here goes with a limited narrowing on a linux install. Any other caching going around for conda?
Again, the no-binary, no-cache works..
```
[daniel test]$ rm -r ~/.cache/pip/
[daniel test]$ conda create -n cyvcf2_test python=3.5
Fetching package metadata: ........
Solving package specifications: .
Package plan for installation in environment /home/daniel/miniconda/envs/cyvcf2_test:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2j-0
    pip:        9.0.1-py35_0
    python:     3.5.2-0
    readline:   6.2-2
    setuptools: 27.2.0-py35_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py35_0
    xz:         5.2.2-0
    zlib:       1.2.8-3

Proceed ([y]/n)?

Linking packages ...
[      COMPLETE      ]|###############################################################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate cyvcf2_test
#
# To deactivate this environment, use:
# $ source deactivate
#
[daniel test]$ source activate cyvcf2_test
discarding /home/daniel/miniconda/bin from PATH
prepending /home/daniel/miniconda/envs/cyvcf2_test/bin to PATH
(cyvcf2_test)[daniel test]$ pip install cyvcf2
Collecting cyvcf2
  Downloading cyvcf2-0.6.5.tar.gz (965kB)
    100% |████████████████████████████████| 972kB 1.4MB/s
Collecting numpy (from cyvcf2)
  Downloading numpy-1.11.2-cp35-cp35m-manylinux1_x86_64.whl (15.6MB)
    100% |████████████████████████████████| 15.6MB 35kB/s
Collecting cython>=0.22.1 (from cyvcf2)
  Downloading Cython-0.25.1-cp35-cp35m-manylinux1_x86_64.whl (7.0MB)
    100% |████████████████████████████████| 7.0MB 178kB/s
Building wheels for collected packages: cyvcf2
  Running setup.py bdist_wheel for cyvcf2 ... done
  Stored in directory: /home/daniel/.cache/pip/wheels/7f/68/93/efa940052e5e7d902a910fea662f854a7ddd691440361a6f72
Successfully built cyvcf2
Installing collected packages: numpy, cython, cyvcf2
Successfully installed cython-0.25.1 cyvcf2-0.6.5 numpy-1.11.2
(cyvcf2_test)[daniel test]$ python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cyvcf2 import VCF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel.nilsson/miniconda/envs/cyvcf2_test/lib/python3.5/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
ImportError: No module named 'cyvcf2.cyvcf2'
```

Installing "sequentially" with 
``` 
pip install numpy
pip install Cython
pip install cyvcf2
```
also seems to work, even in a clean install environment, as above.

**Comment by marcelm** [comment]
The problem occurs when the virtual environment to install into has the `wheel` package already in it, but not `cython` or `numpy`. It can be reproduced in the following way:
```
find ~/.cache/pip/wheels/ -name 'cyvcf2*' -exec rm {} +
pyvenv-3.5 venv
venv/bin/pip3 install wheel
venv/bin/pip3 install cyvcf2
```
(Using `virtualenv` instead will also work because it installs `wheel` by default.)

The `ImportError: No module named 'cyvcf2.cyvcf2'` message is printed because the `cyvcf2.cyvcf2` module is a Cython extension that is never compiled.

This is a bug in the `setup.py` script. In [lines 34-45](https://github.com/brentp/cyvcf2/blob/73b0f3e8e1eab1fda796cfe818d7261646a0d1e5/setup.py#L34-L45), it sets up the list of dependencies by trying to import numpy and Cython. If none of them could be imported, the Cython extension module is *not* compiled.

The suprising part in my opinion is that it does work when the `wheel` package is not installed. In that case, `pip` calls `setup.py egg_info` in order to retrieve the metadata for the package, finding out that `numpy` and `cython` need to be installed, which it does. Afterwards, I assume it calls `setup.py install` in a separate process. Then, because the dependencies have already been installed, the Cython extension module is compiled and installed.

Roughly, the `setup.py` script in its current form relies on the fact that it gets called twice once as `setup.py egg_info` and once as `setup.py install`, but with `wheel` available, only `setup.py bdist_wheel` is called.

**Comment by brentp** [comment]
@marcelm can you recommend a fix?

I usually use bioconda and haven't hit this.

**Comment by marcelm** [comment]
I’m trying to come up with a patch right now. Will open a PR.

**Comment by aleferna** [comment]
My problem was that I didn't have pythondev libs installed, once I installed them then it was fine: 

sudo apt-get install python-dev  
sudo apt-get install python3-dev
